In [7]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
import numpy as np

In [4]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 3.0 MB/s eta 0:00:05
    --------------------------------------- 0.2/12.6 MB 2.1 MB/s eta 0:00:06
    --------------------------------------- 0.2/12.6 MB 1.8 MB/s eta 0:00:07
    --------------------------------------- 0.3/12.6 MB 1.4 MB/s eta 0:00:09
   - -------------------------------------- 0.5/12.6 MB 2.2 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/12.6 MB 2.2 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/12.6 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.6 MB 2.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.1/12.6 MB 2.5 MB/s eta 0:00:05
   --- ------------------------------------ 1.1/12.6 MB 2.5 MB/s eta 0:00:05
   ---- ----------------------------------- 1.5/12.6 MB 2.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.6 MB 2.8 MB/s eta 0:00:04
   ---


[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)

array([[ 0.08427794, -0.2849117 ],
       [-0.82171668, -0.33198486],
       [ 0.75112446, -0.15133604]])

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [10]:
# Basic Math
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [11]:
# Basic Math
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [12]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [13]:
# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [14]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]

array([1, 3, 5])

In [15]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

array([4, 5])

In [17]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [18]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [20]:
# Stacking
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [21]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [26]:
# Save to a file
np.save('array.npy', arr)

In [29]:
# Load from a file
loaded_arr = np.load('array.npy')